name: Building My Sample Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
              cd sample-angular-project
              npm install

      - name: Build Angular project
        run: |
              cd sample-angular-project
              npm run build

      - name: Archive production build
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: sample-angular-project/dist/

      - name: Build and push Docker image
        run: |
          cd sample-angular-project/
          docker build -t ghcr.io/malavshah999/my-angular-app:latest .
          echo "${{ secrets.GITA_TOKENN }}" | docker login ghcr.io -u malavshah999 --password-stdin
          docker push ghcr.io/malavshah999/my-angular-app:latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITA_TOKENN }}" | docker login ghcr.io -u malavshah999 --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: |
          cd sample-angular-project/
          docker push ghcr.io/malavshah999/my-angular-app:latest

